"""
Command-line entry point for the EUVoteAnalyzer pipeline.

Orchestrates all data-collection, preprocessing, and analysis phases.
Each phase is guarded by its own flag so the pipeline can be executed
incrementally (e.g. ``--terms`` on Monday, ``--meps`` on Tuesday).
Test mode redirects all DB writes to an isolated port-3331 database.
"""

import argparse

from EUVoteAnalyzer import *
from typing import Any


def main():
    """
    Parse CLI arguments and dispatch to the appropriate pipeline phase(s).

    Phases (can be combined or run with ``--all``):
        --terms      Fetch parliamentary-term metadata from the EP Open Data API.
        --parties    Fetch political-group and national-party records.
        --meps       Fetch MEP biographies and group memberships.
        --votes      Fetch plenary-session and roll-call vote records.
        --stats      Download and store Eurostat socioeconomic indicators.
        --national   Collect national-parliament composition via Wikipedia + LLM.
        --import     Import an external HowTheyVote CSV dump.
        --prepare    Precompute derived statistics for a term.
        --analyse    Run one or all analysis types and write JSON output files.
        --test       Seed a test database, run preprocessing, and verify analyses.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument('--all', action='store_true', help="Fetches all")
    parser.add_argument('--terms', action='store_true', help="Fetches info about EP terms")
    parser.add_argument('--parties', action='store_true', help="Fetches info about political parties")
    parser.add_argument('--meps', action='store_true', help="Fetches info about MEPs")
    parser.add_argument('--votes', action='store_true', help="Fetches info about voting")
    parser.add_argument('--stats', action='store_true', help="Fetches statistics from Eurostat")
    parser.add_argument('--national', action='store_true', help="Fetches composition of national parliaments from Wikipedia")
    parser.add_argument('--local-cache', type=str, default="cache", help="Path to a local cache directory")
    parser.add_argument('--disable-cache', action='store_true', help="Disable local cache")
    parser.add_argument('--cache-since', type=int, default=100, help="Use local cache only if it was modified within last X days (default is 100)")
    parser.add_argument('--clear-cache', action='store_true', help="Clear local cache")
    parser.add_argument('--clear-database', action='store_true', help="Clear database")
    parser.add_argument('--log-level', type=int, default=0, help="Set verbosity of script(0-INFO, 1-OK, 2-WARN, 3-ERR!OR)")
    parser.add_argument('--data-schema', type=str, default="data-model/schema-EU.json", help="Path to a file with data schema")
    parser.add_argument('--import', action='store_true', help="Import data from dumps into DB")
    parser.add_argument('--htv', action='store_true', help="Import HowTheyVote data (downloads latest release automatically)")
    parser.add_argument('--htv-votes', type=str, metavar='PATH', help="HowTheyVote votes.csv (or .csv.gz) path; overrides auto-download")
    parser.add_argument('--htv-member-votes', type=str, metavar='PATH', help="HowTheyVote member_votes.csv (or .csv.gz) path; overrides auto-download")
    parser.add_argument('--prepare', action='store_true', help="Precompute derived statistics (statistika_clen, statistika_subjekt, byl_pritomen, soudrznost)")
    parser.add_argument('--prepare-term', type=int, metavar='TERM', help="Limit --prepare to a single parliamentary term (zastupitelstvo.poradi)")
    parser.add_argument('--analyse', action='store_true', help="Run analyses (requires --analyse-term and --analyse-type)")
    parser.add_argument('--analyse-term', type=int, metavar='TERM', help="Parliamentary term (zastupitelstvo.poradi) to analyse")
    parser.add_argument('--analyse-type', type=str, metavar='TYPE',
                        choices=['cohesion', 'country', 'inter-faction', 'participation',
                                 'loyalty', 'government-loyalty', 'category-correlate',
                                 'anomally', 'topic-profile',
                                 'deviation-rules', 'opposition-rules', 'mep-pairs', 'all'],
                        default='all',
                        help="Analysis type: cohesion | country | inter-faction | participation | loyalty | government-loyalty | category-correlate | anomally | topic-profile | deviation-rules | opposition-rules | mep-pairs | all")
    parser.add_argument('--show-dumps', action='store_true', help="Print content of files generated by analyses")
    parser.add_argument('--output-dir', type=str, default='web/data', help="Directory to save analysis JSON output (default: web/data)")
    parser.add_argument('--test', action='store_true', help="Run tests")
    parser.add_argument('--test-init', action='store_true', help="Initialize test database with seed data and run preprocessing")
    parser.add_argument('--test-run', action='store_true', help="Run analyses against test database and compare with ground truth")
    parser.add_argument('--eval-log', action='store_true', help="Run the NationalFetch extraction evaluation harness over test/ground_truth_extraction and write logs/extraction_eval")
    parser.add_argument('--eval-content-mode', type=str, choices=['html', 'markdown', 'raw'], default='html',
                        help="Content-reduction mode for --eval-log: html (production baseline), markdown (WikiLoader ablation), raw (no reduction ablation)")
    parser.add_argument('--eval-ground-truth-dir', type=str, default='EUVoteAnalyzer/test/ground_truth_extraction',
                        help="Directory of ground-truth JSON files to drive --eval-log")
    parser.add_argument('--eval-log-dir', type=str, default='logs/extraction_eval', help="Output directory for --eval-log records")
    args = parser.parse_args()

    ProgressPrint.setup(args.log_level)

    if args.test or args.test_init or args.test_run:
        DB.use_test_port(3331)
        ProgressPrint.log("Test mode: using database on port 3331", "INFO")

    local_cache = LocalCache(args.local_cache, args.cache_since)
    SmartLoader.setup(local_cache if not args.disable_cache else None)
    SmartSparqlQuery.setup(local_cache if not args.disable_cache else None)
    SmartLLM.setup(local_cache if not args.disable_cache else None, "gemini", GEMINI_API_KEY, "gemini-2.5-flash", support_json=True, rpm=1500, tpm=3000000, rpd=0)
    schema_manager = SchemaManager(args.data_schema)
    schema_manager.load()

    if args.clear_cache or args.clear_database:
        if args.clear_cache:
            LocalCache.clear_cache(args.local_cache)
        if args.clear_database:
            schema_manager.drop_tables()
        ErrorHandler.print()
        return

    if args.test or args.test_init:
        schema_manager.drop_tables()

    schema_manager.create_tables()
    schema_manager.existing_tables({})

    if args.test or args.test_init or args.test_run:
        tester = Tester()
        if args.test or args.test_init:
            tester.init()
            if args.test:
                ProgressPrint.log("Test database initialized.", "OK")
            else:
                ProgressPrint.log("Test database initialized. Run with --test-run to verify.", "OK")
            if args.test_init:
                ErrorHandler.print()
                return
    
        if args.test or args.test_run:
            tester.run()
            ProgressPrint.log("Tests finished", "OK")
            ErrorHandler.print()
            return

    if args.clear_cache:
        LocalCache.clear_cache(args.local_cache) 

    if args.terms or args.all: 
        terms_fetch = TermsFetch()
        terms_fetch.do(disable_cache=args.disable_cache, local_cache=local_cache)    

    if args.parties or args.all:
        parties_fetch = PartiesFetch()
        parties_fetch.do(disable_cache=args.disable_cache, local_cache=local_cache)

    if args.meps or args.all:
        meps_fetch = MepsFetch()
        meps_fetch.do(disable_cache=args.disable_cache, local_cache=local_cache)

    if args.votes or args.all:
        votes_fetch = VotesFetch(False)
        votes_fetch.do(disable_cache=args.disable_cache, local_cache=local_cache)

    if args.stats or args.all:
        stats_fetch = StatsFetch(False)
        stats_fetch.do()

    if args.national or args.all:
        LLM.setup(provider="gemini", model="gemini-2.5-flash", api_key=GEMINI_API_KEY, support_json=True, rpm=1500, tpm=3000000, rpd=0)
        national_fetch = NationalFetch()
        national_fetch.do(local_cache=local_cache)

    if args.eval_log:
        import glob
        import json
        import os
        LLM.setup(provider="gemini", model="gemini-2.5-flash", api_key=GEMINI_API_KEY, support_json=True, rpm=1500, tpm=3000000, rpd=0)
        out_dir = args.eval_log_dir if args.eval_content_mode == "html" else f"{args.eval_log_dir}_ablation_{args.eval_content_mode}"
        os.makedirs(out_dir, exist_ok=True)
        national_eval = NationalFetch()
        gt_files = sorted(glob.glob(os.path.join(args.eval_ground_truth_dir, "*.json")))
        if not gt_files:
            ProgressPrint.log(f"No ground-truth files found in {args.eval_ground_truth_dir}", "ERR!")
        for gt_path in gt_files:
            with open(gt_path, encoding="utf-8") as f:
                gt = json.load(f)
            country = gt["country"]
            election_year = gt["election_year"]
            ProgressPrint.log(f"Evaluating extraction for {country} {election_year} ({args.eval_content_mode})", "INFO")
            record = national_eval.eval_extract_one(
                country, election_year,
                content_mode=args.eval_content_mode,
                fallback_wikipedia_url=gt.get("wikipedia_url"),
            )
            gt_slug = (gt.get("wikipedia_url") or "").rstrip("/").split("/wiki/")[-1] or None
            record["phase_1_source_acquisition"]["matches_ground_truth"] = (
                gt_slug is not None and record["phase_1_source_acquisition"]["discovered_slug"] == gt_slug
            )
            out_path = os.path.join(out_dir, f"{country}_{election_year}.json")
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(record, f, ensure_ascii=False, indent=2)
            ProgressPrint.log(f"Wrote {out_path}", "OK")
        ProgressPrint.log(f"Evaluation logs written to {out_dir}", "OK")
        ErrorHandler.print()
        return

    if getattr(args, 'import') or args.all:
        if args.htv or args.htv_votes or args.htv_member_votes:
            HtvImport().do(args.htv_votes, args.htv_member_votes)

    if args.prepare:
        Preprocessor().do(term=args.prepare_term)

    if args.analyse:
        import json
        import os

        if args.analyse_term is None:
            ProgressPrint.log("--analyse requires --analyse-term", "ERR!")
        else:
            analyser = Analyser()
            t = args.analyse_term
            kind = args.analyse_type
            out_dir = os.path.join(args.output_dir, f"term_{t}")
            os.makedirs(out_dir, exist_ok=True)

            def _dump(label: str, data: Any, filename: str) -> None:
                """Print *data* as formatted JSON and persist it to *out_dir/filename*.json."""
                ProgressPrint.log(f"=== {label} ===", "OK")
                if args.show_dumps:
                    print(json.dumps(data, ensure_ascii=False, default=str, indent=2))
                path = os.path.join(out_dir, f"{filename}.json")
                with open(path, "w", encoding="utf-8") as _f:
                    json.dump(data, _f, ensure_ascii=False, default=str, indent=2)
                ProgressPrint.log(f"Saved → {path}", "OK")

            if kind in ('cohesion', 'all'):
                _dump(f"Party cohesion (term {t})", analyser.party_cohesion(t), "party_cohesion")

            if kind in ('country', 'all'):
                _dump(f"Country cohesion (term {t})", analyser.country_cohesion(t), "country_cohesion")

            if kind in ('inter-faction', 'all'):
                _dump(f"Inter-faction cohesion (term {t})", analyser.inter_faction_cohesion(t), "inter_faction_cohesion")

            if kind in ('participation', 'all'):
                _dump(f"MEP participation (term {t})", analyser.mep_participation(t), "mep_participation")

            if kind in ('loyalty', 'all'):
                _dump(f"MEP loyalty (term {t})", analyser.mep_loyalty(t), "mep_loyalty")

            if kind in ('government-loyalty', 'all'):
                _dump(f"Government/opposition loyalty (term {t})",
                      analyser.government_opposition_loyalty(t),
                      "government_opposition_loyalty")

            if kind == 'anomally':
                n = analyser.export_all_mep_anomalies(t, out_dir, final_only=True)
                ProgressPrint.log(f"Exported anomaly data for {n} MEPs → {out_dir}/anomalous_votes/", "OK")

            if kind in ('category-correlate', 'all'):
                _dump(f"Category correlations with socioeconomic indicators (term {t})",
                      analyser.correlate_categories_with_indicators(t),
                      "category_correlations")

            if kind in ('topic-profile', 'all'):
                _dump(f"Party topic profiles (term {t})",
                      analyser.party_topic_profile(t),
                      "party_topic_profile")

            if kind in ('deviation-rules', 'all'):
                _dump(f"Topic deviation rules (term {t})",
                      analyser.topic_deviation_rules(t),
                      "topic_deviation_rules")

            if kind in ('opposition-rules', 'all'):
                _dump(f"Faction opposition rules (term {t})",
                      analyser.faction_opposition_rules(t),
                      "faction_opposition_rules")

            if kind == 'mep-pairs':
                n = analyser.export_all_mep_comparisons(t, out_dir)
                ProgressPrint.log(f"Exported MEP pair comparisons ({n} files) → {out_dir}/mep_comparison/", "OK")

    ErrorHandler.print()

if __name__ == '__main__':
    main()